#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "usage: $0 path" >&2
  echo "       compile and immediately run the .bitsy file at path" >&2
  exit 1
fi

BITSYPATH=bin
BITSYNAME=bitsy-swift
RUNARG="--run-delete"

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
BITSYBIN=$SCRIPTPATH/$BITSYPATH/$BITSYNAME

if [ ! -f "$BITSYBIN" ]; then
  echo "[ERROR] $BITSYNAME has not been built" >&2
  echo "-> Run build.sh in $SCRIPTPATH" >&2
  exit 1
fi

$BITSYBIN $1 $RUNARG
